production:
  
  auto_deploy_on: refs/heads/master
  required_contexts: ['ci_collab']
  environment: production
  production_environment: true

staging:
  auto_deploy_on: refs/heads/master
  required_contexts: ["ci_worker"]
  environment: staging
  production_environment: false