production:
  # required_contexts: ['ci_collab']
  auto_deploy_on: refs/heads/master
  environment: production
  production_environment: true

staging:
  required_contexts: ['ci_worker']
  auto_deploy_on: refs/heads/master
  environment: staging
  production_environment: false