production:
  auto_deploy_on: refs/heads/master
  required_contexts: ['ci_collab']
  environment: alpha
  production_environment: true

staging:
  auto_deploy_on: refs/heads/master
  required_contexts: ["ci_worker"]
  environment: alpha
  production_environment: false