name: ci_worker

on:
  push:
    paths:
      # run on changes to all files (other than the ones ignored above)
      - 'packages/worker/**'

jobs:
  build:

    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@master'
    - name: 'Test'
      run: 'echo "ok"'
    - name: 'Done'
      run: 'exit 0'